### ISSUE TITLE
08_PointOfInterest_1_PoiAtLocation sample not working

### ISSUE THREAD

**Issue by eidmuha** [mkoehne/WikitudeExample#1]
Hi, Thank you for providing this project on GitHub. 

Everything work fine except the samples with that contain finding the location. The Samples work fine on the Wikitude App on my mobile. Can you please explain why the samples such as _08_PointOfInterest_1_PoiAtLocation_ is not working? 

As per my research **architectView.setLocation** is not called anywhere in the project, can you explain how does the sample retrieve the latitude, longitude and altitude values?

**Comment by mkoehne** [comment]
Hi, sorry for the late response.

Could you give me a bit more information like what OS you are using and if you have location service enabled?

On iOS wikitude should use the native location service to retrieve latitude, longitude and altitude.
So for this to work you need to have location service enabled and click allow when the pop up asks if the application could use your position.
