### ISSUE TITLE
Visual Studio No Longer Supports Xamarin Components

### ISSUE THREAD

**Issue by kenneymyers** [mkoehne/WikitudeExample#2]
Do you have a new version by chance that uses nuget packages instead of Xamarin Components since Microsoft no longer allows you to build solutions that use Xamarin Components?

**Comment by mkoehne** [comment]
Hi,
the nuget version from wikitude is not working for me. 
I updated the project with local libs from the Wikitude website.
Please follow the instructions from readme and than you should be able to use version 7.2.0 without Xamarin Components.

**Comment by kenneymyers** [comment]
It's not clear to me from the readme where you want me to extract the
components or what else is required to make the project build.  As of right
now the project doesn't build as is without some manual intervention.  Can
you specify what the final project/folder structure should look like please?

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Official FaceBook Page: https://www.facebook.com/kenneymyers
Instagram: https://www.instagram.com/kenneymyers
IMDB: https://www.imdb.me/kenneymyers
Website: http://www.kenneymyers.com
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by mkoehne** [comment]
I have updated the readme. 
You have to copy two files (Wikitude.SDK.dll) from the com.wikitude.xamarin.component-7.2.0 folder into the project. I placed a txt file in each the folder where the DLLs belong.
Structure should look like this:
WikitudeExample
    - Libs
        - android
              - Wikitude.SDK.dll
        - ios-unified
              - Wikitude.SDK.dll

Hope that makes more sense.

**Comment by kenneymyers** [comment]
When I attempt to run it for android I get:
Failed resolution of: Landroid/support/v7/appcompat/R$attr;

This was fixed by just updating all packages so all good.  Thanks!

**Comment by mkoehne** [comment]
Great :)
